"""
HTML Reporter
=============
Renders an AuditReport as a self-contained HTML file with no external
dependencies at render time (all CSS is inlined).

Usage
-----
>>> from ai_critic.reporters.html import save_html_report
>>> save_html_report(report, "audit_report.html")
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Union

from ai_critic.core.types import AuditReport, Verdict

_VERDICT_COLOR = {
    Verdict.PASS: "#22c55e",
    Verdict.WARNING: "#f59e0b",
    Verdict.FAIL: "#ef4444",
}
_VERDICT_ICON = {
    Verdict.PASS: "✅",
    Verdict.WARNING: "⚠️",
    Verdict.FAIL: "❌",
}

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Model Audit Report</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: system-ui, -apple-system, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
  h1 {{ font-size: 1.5rem; font-weight: 700; margin-bottom: 0.25rem; }}
  .subtitle {{ color: #94a3b8; font-size: 0.875rem; margin-bottom: 2rem; }}
  .card {{ background: #1e293b; border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }}
  .overall {{ display: flex; align-items: center; gap: 2rem; flex-wrap: wrap; }}
  .big-score {{ font-size: 3.5rem; font-weight: 800; line-height: 1; }}
  .verdict-badge {{ font-size: 1rem; font-weight: 600; padding: 0.4rem 1rem; border-radius: 999px; }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ text-align: left; padding: 0.75rem 1rem; font-size: 0.75rem; text-transform: uppercase;
        letter-spacing: 0.05em; color: #64748b; border-bottom: 1px solid #334155; }}
  td {{ padding: 0.75rem 1rem; border-bottom: 1px solid #1e293b; font-size: 0.875rem; }}
  tr:last-child td {{ border-bottom: none; }}
  .bar-wrap {{ background: #0f172a; border-radius: 4px; height: 6px; width: 120px; }}
  .bar {{ height: 6px; border-radius: 4px; }}
  .suggestions {{ list-style: none; }}
  .suggestions li {{ padding: 0.5rem 0; border-bottom: 1px solid #334155; font-size: 0.875rem; color: #94a3b8; }}
  .suggestions li::before {{ content: "→ "; color: #f59e0b; }}
  .suggestions li:last-child {{ border-bottom: none; }}
  .meta {{ color: #64748b; font-size: 0.75rem; margin-top: 1rem; }}
  h2 {{ font-size: 1rem; font-weight: 600; margin-bottom: 1rem; color: #94a3b8; }}
  .json-section {{ background: #0f172a; border-radius: 8px; padding: 1rem; font-size: 0.75rem;
                   font-family: monospace; white-space: pre-wrap; color: #94a3b8; overflow-x: auto; }}
</style>
</head>
<body>
<h1>🔍 Model Audit Report</h1>
<p class="subtitle">Generated by ai-critic · Problem type: {problem_type}</p>

<div class="card">
  <div class="overall">
    <div>
      <div style="font-size:0.75rem;color:#64748b;margin-bottom:0.25rem">OVERALL SCORE</div>
      <div class="big-score" style="color:{overall_color}">{overall_score:.3f}</div>
    </div>
    <div>
      <span class="verdict-badge" style="background:{overall_color}22;color:{overall_color}">
        {verdict_icon} {overall_verdict}
      </span>
    </div>
  </div>
</div>

<div class="card">
  <h2>DIMENSIONS</h2>
  <table>
    <thead>
      <tr>
        <th>Dimension</th>
        <th>Score</th>
        <th></th>
        <th>Verdict</th>
        <th>Summary</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>
</div>

{suggestions_section}

<div class="card">
  <h2>RAW JSON</h2>
  <div class="json-section">{json_data}</div>
</div>

<p class="meta">ai-critic · <a href="https://pypi.org/project/ai-critic/" style="color:#3b82f6">PyPI</a></p>
</body>
</html>"""


def _dim_row(dim) -> str:
    color = _VERDICT_COLOR[dim.verdict]
    icon = _VERDICT_ICON[dim.verdict]
    pct = int(dim.score * 100)
    summary = dim.summary[:80] + "…" if len(dim.summary) > 80 else dim.summary
    return (
        f"<tr>"
        f"<td><strong>{dim.name}</strong></td>"
        f"<td style='color:{color}'>{dim.score:.3f}</td>"
        f"<td><div class='bar-wrap'><div class='bar' style='width:{pct}%;background:{color}'></div></div></td>"
        f"<td style='color:{color}'>{icon} {dim.verdict.value}</td>"
        f"<td style='color:#94a3b8'>{summary}</td>"
        f"</tr>"
    )


def save_html_report(report: AuditReport, path: Union[str, Path] = "audit_report.html") -> Path:
    """
    Render the AuditReport as a self-contained HTML file.

    Parameters
    ----------
    report : AuditReport returned by ai_critic.audit()
    path   : output file path (default: "audit_report.html")

    Returns
    -------
    Path of the written file.
    """
    path = Path(path)

    dims_sorted = sorted(report.dimensions.values(), key=lambda d: d.score)
    rows = "\n      ".join(_dim_row(d) for d in dims_sorted)

    suggestions_html = ""
    if report.top_suggestions:
        items = "\n".join(f"<li>{s}</li>" for s in report.top_suggestions)
        suggestions_html = (
            f'<div class="card"><h2>TOP SUGGESTIONS</h2>'
            f'<ul class="suggestions">{items}</ul></div>'
        )

    overall_color = _VERDICT_COLOR[report.overall_verdict]
    verdict_icon = _VERDICT_ICON[report.overall_verdict]

    html = _TEMPLATE.format(
        problem_type=report.problem_type.value,
        overall_score=report.overall_score,
        overall_color=overall_color,
        overall_verdict=report.overall_verdict.value.upper(),
        verdict_icon=verdict_icon,
        rows=rows,
        suggestions_section=suggestions_html,
        json_data=json.dumps(report.to_dict(), indent=2),
    )

    path.write_text(html, encoding="utf-8")
    return path